#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2019-present Team LibreELEC (https://libreelec.tv)

# copy amlogic autoscript files to part1
mcopy $PROJECT_DIR/$PROJECT/bootloader/bootscript/aml_autoscript ::/aml_autoscript
